import './includes/accordion';
import './includes/accounts';
import './includes/cart-drawer';
import './includes/collection';
import './includes/faq-tab-links';
import './includes/form-custom-dropdown';
import './includes/misc';
import './includes/navbar';
import './includes/newsletter-popup';
import './includes/product';
import './includes/scroll';
import './includes/search';
import './includes/tabs';
import './includes/terms';
import './includes/toggle-switch';
import './includes/contact-tabs'
import './includes/faq-navbar'
import './includes/privacy-navbar'
import './includes/contact-nav'
